package com.teusoft.lono.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.teusoft.lono.dao.Lono;

import com.teusoft.lono.dao.LonoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lonoDaoConfig;

    private final LonoDao lonoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lonoDaoConfig = daoConfigMap.get(LonoDao.class).clone();
        lonoDaoConfig.initIdentityScope(type);

        lonoDao = new LonoDao(lonoDaoConfig, this);

        registerDao(Lono.class, lonoDao);
    }
    
    public void clear() {
        lonoDaoConfig.getIdentityScope().clear();
    }

    public LonoDao getLonoDao() {
        return lonoDao;
    }

}
