package com.teusoft.lono.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LONO.
 */
public class Lono {

    private Long id;
    private Integer temperature;
    private Integer humidity;
    private Long timeStamp;
    private Integer channel;
    private Integer index;

    public Lono() {
    }

    public Lono(Long id) {
        this.id = id;
    }

    public Lono(Long id, Integer temperature, Integer humidity, Long timeStamp, Integer channel, Integer index) {
        this.id = id;
        this.temperature = temperature;
        this.humidity = humidity;
        this.timeStamp = timeStamp;
        this.channel = channel;
        this.index = index;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTemperature() {
        return temperature;
    }

    public void setTemperature(Integer temperature) {
        this.temperature = temperature;
    }

    public Integer getHumidity() {
        return humidity;
    }

    public void setHumidity(Integer humidity) {
        this.humidity = humidity;
    }

    public Long getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(Long timeStamp) {
        this.timeStamp = timeStamp;
    }

    public Integer getChannel() {
        return channel;
    }

    public void setChannel(Integer channel) {
        this.channel = channel;
    }

    public Integer getIndex() {
        return index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

}
